language: objective-c
before_install:
  - sudo easy_install cpp-coveralls
script: 
  - xcodebuild -workspace ADALiOS.xcworkspace -scheme ADALiOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -workspace ADALiOS.xcworkspace -scheme ADALiOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success:
  - coveralls -e ADALiOS/ADALiOSTests

